# Generated by Django 2.1.5 on 2023-07-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='auther',
            new_name='author',
        ),
    ]
