# Generated by Django 2.1.5 on 2023-07-11 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-last_update_time']},
        ),
    ]
